### ISSUE TITLE
Upvote counter

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#12]
Each app card should have a button whose caption is the upvote count and on click should increment the counter.

Reference: [ProductHunt](https://www.producthunt.com/)
![image](https://cloud.githubusercontent.com/assets/4335188/15215143/4596d7de-1827-11e6-9d93-05c61a492476.png)

The user should be logged in to perform this action and only an upvote per user is permitted.

**Comment by Annagramma** [comment]
Hey @jfresco 
Is it deployed yet?
I can't find it on staging.

**Comment by jfresco** [comment]
@Annagramma not yet. I'll let you know.
