### ISSUE TITLE
Add Segment

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#13]
In order to get insights about app usage.

**Comment by gvilarino** [comment]
@Annagramma you should be sync'd with progress here

**Comment by Annagramma** [comment]
I'm on it! :)

2016-05-12 11:53 GMT-03:00 Guido Vilariño notifications@github.com:

> @Annagramma https://github.com/Annagramma you should be sync'd with
> progress here
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/DemocraciaEnRed/civicstack/issues/13#issuecomment-218782208

## 

Ana Lis Rodríguez Nardelli

S: analisrn
@annagramma
