### ISSUE TITLE
Show applied filters

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#21]
Including tags, countries and technologies.

**Comment by juanpernu** [comment]
Applied Filters
![image](https://cloud.githubusercontent.com/assets/4269424/16431419/dac96eee-3d56-11e6-8b0e-4342138b067c.png)

Select Filter
![image](https://cloud.githubusercontent.com/assets/4269424/16431427/e3371784-3d56-11e6-9b23-512318994bfe.png)

**Comment by jfresco** [comment]
Let's discuss the design in #30.
