### ISSUE TITLE
Integrate with MailChimp

### ISSUE THREAD

**Issue by jfresco** [DemocraciaEnRed/civicstack#23]
- [ ] Make a script that adds existing user's emails to a MailChimp list
- [ ] Modify the app in order to add new users to the list

**Comment by gvilarino** [comment]
Can't this be done with `nodemailer`?

**Comment by mjlescano** [comment]
Not the list managing part. This issue is to be able to have an updated mailing list, for newsletter/communication purposes from mailchimp, not for doing the mailing itself.
