### ISSUE TITLE
Some projects are offline

### ISSUE THREAD

**Issue by martinszy** [DemocraciaEnRed/civicstack#3]
I've seen three projects and two of them were broken or offline.
A proposal to solve this problem is that civicstack monitors the URLs of the apps regularly, include a field on weather or not they are serving content, and maybe use this field to group the results, prioritizing those which are online.

**Comment by mairwilliams** [comment]
It would be really helpful to know specifically which projects with broken links you opened.

**Comment by martinszy** [comment]
One of them was the one about femicides in Bolivia, the other I don't remember now.

**Comment by gvilarino** [comment]
@martinszy PRs are welcome :)

**Comment by mjlescano** [comment]
All the offline projects were removed :)
