### ISSUE TITLE
Design feature categories for homepage

### ISSUE THREAD

**Issue by Annagramma** [DemocraciaEnRed/civicstack#36]
- arrange predetermined categories on the homepage
- use them as filters for the apps
- Product Hunt inspiration: [https://www.producthunt.com/](url)
  ![image](https://cloud.githubusercontent.com/assets/4205060/16384166/51181a86-3c5e-11e6-92a0-20c7ca7d527f.png)
  @juanpernu

**Comment by juanpernu** [comment]
![image](https://cloud.githubusercontent.com/assets/4269424/16431336/81e1bf02-3d56-11e6-881c-a12d148fcad7.png)
