### ISSUE TITLE
How to adapt civicstack to a different language?

### ISSUE THREAD

**Issue by madcsaba** [DemocraciaEnRed/civicstack#6]
Hi, we would love to do smthg like civicstack in Hungarian.
What do you suggest?
Is it esasier to translate it, or shall we use the content and build a new site in Hungarian?

Thanks in advance!

**Comment by sachalifs** [comment]
Inside [this dir](https://github.com/DemocraciaEnRed/civicstack/tree/development/lib/translations/lib) we have the languages file.

We encourage you to get the English one translated to Hungarian if you would like. We're planning a roadmap for **CivicStack 2016** and it might include many more languages!
